#!/usr/bin/env python
# vim: ft=python

import sys
import csv

class Colors:
  TABLE = {
      'black' : '\033[30m',
      'red' : '\033[31m',
      'green' : '\033[32m',
      'yellow' : '\033[33m',
      'blue' : '\033[34m',
      'magenta' : '\033[35m',
      'cyan' : '\033[36m',
      'white' : '\033[37m',
      'reset' : '\033[39m'
  }
  def prn(self, color, string):
    return self.TABLE['reset']+self.TABLE[color]+string+self.TABLE['reset']

class PrettyT:
  def extract(self, line):
    try:
      t_id, time, user, status = csv.reader([line])
      return [t_id, time, user,status]
    except:
      return [False, False, False, line] # lolz

  def processLine(self, line):
    tmpl = """--
    | @{0} / {1} / {2}
    | {3}
    """
    d = self.extract(line)
    if d[0] and d[1]:
      return tmpl.format(d)
    else:
      return ""


t = PrettyT()

for line in iter(sys.stdin.readline, ""):
  print line
  print t.processLine(line)
