#!/usr/bin/env python
# vim: ft=python

import sys
import csv

class Colors:
  TABLE = {
      'black' : '\033[30m',
      'red' : '\033[31m',
      'green' : '\033[32m',
      'yellow' : '\033[33m',
      'blue' : '\033[34m',
      'magenta' : '\033[35m',
      'cyan' : '\033[36m',
      'white' : '\033[37m',
      'reset' : '\033[39m'
  }
  def prn(self, color, string):
    return self.TABLE['reset']+self.TABLE[color]+string+self.TABLE['reset']

class PrettyT:

  tmpl = '''--
| @{user} / {_id} / {time}
| {body}'''

  def extract(self, line):
    d = []
    try:
      for _ in csv.reader([line]):
        d.append(_)
    except csv.Error: # \n in status body! or some other crap
      try:
        ex = line.split(',',3)
      except ValueError:
        ex = line

      d.append(ex)



    return d[0]

  def processLine(self, line,colorizer):
    d = self.extract(line)
    if len(d) > 1:
      t_id, time,user,status = d
      ok = True
    else:
      ok = False
      status = line

    if ok:
      u = colorizer.prn('green',user)
      i = colorizer.prn('yellow',t_id)
      t = colorizer.prn('white', time)
      return self.tmpl.format(user=u, _id=i, time=t, body=status)
    else:
      return "| "+status


t = PrettyT()
c = Colors()

for line in iter(sys.stdin.readline, ""):
  print t.processLine(line,c)
